[tool.poetry]
name = "metadata3dExtractionLambdaLayer"
version = "0.1.0"
description = ""
authors = ["Kurt Scheuringer <scheurik@amazon.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^10.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
